export const REGISTER_INITIATE = "REGISTER_INITIATE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERRORS = "AUTH_ERRORS";

export const LOGIN_INITIATE = "LOGIN_INITIATE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
