export const GET_POSTS_INITIATE = "GET_POSTS_INITIATE";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const UPDATE_LIKES = "UPDATE_LIKES";
export const REMOVE_LIKES = "REMOVE_LIKES";
